Kubator/urls.py
from django.conf.urls import handler404
"""Kubator URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
    path('service/', include('service.urls')),
    path('manager/', include('manager.urls')),
]


handler404 = 'account.views.error_404_view'
handler500 = 'account.views.error_500_view'

account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'
urlpatterns = [
    path('', views.index, name='home'),
    path('sign-up/<str:profile>/', views.signup, name='signup'),
]

manager/models.py
from django.db import models
from django.contrib.auth.models import User


class ManagerProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    middle_name = models.CharField(max_length=100, verbose_name="Отчество")

service/models.py
from django.db import models
from django.contrib.auth.models import User


class Position(models.Model):
    title = models.CharField(
        max_length=100, unique=True, verbose_name="Должность")

    def __str__(self):
        return self.title


class MedWorkerProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                verbose_name="Пользователь")
    raw_password = models.CharField(max_length=8, verbose_name="Пароль")
    middle_name = models.CharField(max_length=100, verbose_name="Отчество")
    position = models.ForeignKey(
        'Position',
        on_delete=models.CASCADE,
        verbose_name='Должность'
    )

    def __str__(self):

        return f'{self.user.last_name} {self.user.first_name[0]}. {self.middle_name[0]}.'


class Ward(models.Model):
    number = models.CharField(max_length=2, verbose_name='Номер палаты')

    def __str__(self):
        return self.number


class PatientProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                verbose_name="Пользователь")
    raw_password = models.CharField(max_length=8, verbose_name="Пароль")
    ward = models.ForeignKey(Ward, on_delete=models.CASCADE, verbose_name="Номер палаты")
    middle_name = models.CharField(max_length=100, verbose_name="Отчество")
    birth_date = models.DateField(null=False, verbose_name="Дата рождения")
    address = models.TextField(verbose_name="Адрес")
    contact_phone = models.CharField(max_length=16,
                                     verbose_name="Контактный телефон")

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name}'


class Service(models.Model):
    name = models.CharField(max_length=120, verbose_name="Наименование услуги")

    def __str__(self):
        return self.name


class OrderStatus(models.Model):
    name = models.CharField(max_length=20, unique=True,
                            verbose_name='Наименование статуса')
    done = models.BooleanField(verbose_name='Заявка закрыта', default=False)

    def __str__(self):
        return self.name


class Order(models.Model):
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    worker = models.ForeignKey(MedWorkerProfile, on_delete=models.CASCADE,
                               blank=True, null=True)

    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    status = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
    report = models.TextField(blank=True, null=True)

    creation_date = models.DateTimeField(auto_now_add=True, auto_now=False,
                                         verbose_name='Дата поступления заявки')

    opening_date = models.DateTimeField(auto_now_add=False, auto_now=False,
                                        blank=True, null=True,
                                        verbose_name='Дата открытия заявки')

    closing_date = models.DateTimeField(auto_now_add=False, auto_now=False,
                                        blank=True, null=True,
                                        verbose_name='Дата закрытия заявки')

    def __str__(self):
        return f"{self.patient.user.username} {self.service.name}"

manager/forms.py
from django import forms
from service.models import PatientProfile, MedWorkerProfile, Ward, Position


class SignUpPatientForm(forms.ModelForm):
    last_name = forms.CharField(label='', max_length=100)
    first_name = forms.CharField(label='', max_length=100)
    birth_date = forms.DateField(label='',
                                 widget=forms.DateInput(
                                     attrs={'type': 'date'}))
    ward = forms.ModelChoiceField(queryset=Ward.objects.all(),
                                  empty_label='Палата',
                                  label='')

    class Meta:
        model = PatientProfile
        fields = ['last_name', 'first_name', 'middle_name',
                  'birth_date', 'address', 'contact_phone', 'ward']


class SignUpMedWorkerForm(forms.ModelForm):
    last_name = forms.CharField(label='', max_length=100)
    first_name = forms.CharField(label='', max_length=100)
    position = forms.ModelChoiceField(queryset=Position.objects.all(),
                                      empty_label='Должность',
                                      label='')

    class Meta:
        model = MedWorkerProfile
        fields = ['last_name', 'first_name', 'middle_name',
                  'position']

manager/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from .forms import SignUpPatientForm, SignUpMedWorkerForm
from .models import ManagerProfile
from .helpers import gen_username, is_manager
from service.models import Order, OrderStatus
from service.handler import OrderDistributor
from django.utils import timezone


@user_passes_test(is_manager, redirect_field_name='', login_url='account:home')
def index(request):

    def find_worker_by_order(order_id):
        dsys = OrderDistributor()
        order_obj = Order.objects.get(id=order_id)
        for key, val in dsys.workers.items():
            if val == order_obj:
                return key

    def close(order_id):
        dsys = OrderDistributor()
        worker_id = find_worker_by_order(order_id)
        dsys.close(worker_id, "Закрыто менеджером")

    if request.method == 'POST':
        if 'redirect' in request.POST:
            if request.POST['redirect'] == 'medworker':
                return redirect('manager:signup', 'medworker')
            elif request.POST['redirect'] == 'patient':
                return redirect('manager:signup', 'patient')
        elif 'close-order' in request.POST:
            close(request.POST['close-order'])
            # order_id = request.POST['close-order']
            # status_done = OrderStatus.objects.get(name='Выполнено')
            # order = Order.objects.filter(pk=order_id).update(
            #     status=status_done,
            #     report='Закрыто менеджером',
            #     closing_date=timezone.now())
            return redirect('manager:home')
    else:
        try:
            middle_name = ManagerProfile.objects.get(
                user=request.user.pk).middle_name
        except ManagerProfile.DoesNotExist:
            middle_name = ''
        status_new = OrderStatus.objects.get(name='Ожидает исполнения')
        status_proc = OrderStatus.objects.get(name='В процессе')
        status_done = OrderStatus.objects.get(name='Выполнено')
        new_orders = Order.objects.filter(status=status_new)
        in_proc_orders = Order.objects.filter(status=status_proc)
        done_orders = Order.objects.filter(status=status_done)
        context = {'last_name': request.user.last_name,
                   'first_name': request.user.first_name,
                   'middle_name': middle_name,
                   'new_orders': new_orders,
                   'in_proc_orders': in_proc_orders,
                   'done_orders': done_orders}
        return render(request, 'manager/manager_cab.html', context)


@user_passes_test(is_manager, redirect_field_name='', login_url='account:home')
def signup(request, profile):
    if request.method == 'POST':
        if profile == 'patient':
            form = SignUpPatientForm(request.POST)
        elif profile == 'medworker':
            form = SignUpMedWorkerForm(request.POST)
        if form.is_valid():
            user = User()
            username = gen_username(profile)
            user.username = username
            password = User.objects.make_random_password(length=8)
            user.set_password(password)
            user.last_name = form.cleaned_data['last_name']
            user.first_name = form.cleaned_data['first_name']
            user.save()
            group = Group.objects.get(name=profile)
            group.user_set.add(user)
            profile = form.save(commit=False)
            profile.user = user
            profile.raw_password = password
            profile.save()
            context = {'username': username,
                       'password': password}
            return render(request, 'manager/login_password.html', context)
    else:
        if profile == 'patient':
            form = SignUpPatientForm()
            return render(request, 'manager/patient_sign_up.html', {'form': form})
        elif profile == 'medworker':
            form = SignUpMedWorkerForm()
            return render(request, 'manager/medworker_sign_up.html', {'form': form})
        else:
            raise Http404()
    return render(request, 'manager/sign_up.html', {'form': form})

manager/templates/manager/login_password.html
{% extends 'base.html' %}


{% block title %}
<title> Логин и пароль </title>
{% endblock title %}


{% block content  %}

    <div class="container">
        <form action="{% url 'manager:home' %}">
            <button type="submit" class="btn btn-default">Кабинет</button>
        </form>
        <div id="cc">
            <h3>Логин:</h3>
            <h1>{{username}}</h1>
        </div><br><br><br>
        <div id="cc">
            <h3>Пароль:</h3>
            <h1>{{password}}</h1>
        </div><br><br><br>
    </div>

{% endblock content  %}

manager/templates/manager/manager_cab.html
{% extends 'base.html' %}


{% block js %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
{% endblock js %}


{% block title %}
<title> Личный кабинет менеджера </title>
{% endblock title %}


{% block content %}
<div class="container">
    <div class="float-right">
        <form action="{% url 'account:logout' %}"><button type="sumbit" class="btn btn-default">Выход</button></form>
    </div><br><br>
    <div class="h1">Добро пожаловать!</div>
    <div class="h3">{{last_name}} {{first_name}} {{middle_name}}</div>
    <br>
    <div id='cc'>
        <form method='post'>
            {% csrf_token %}
            <button type="sumbit" class="btn btn-default" id="manag_but" name='redirect' value='medworker'>Зарегистрировать
                работника</button>
            <button type="sumbit" class="btn btn-default" id="manag_but" name='redirect' value='patient'>Зарегистрировать
                пациентку</button>
        </form>
    </div><br>
    <div>
        <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="nav" id="new-tab" data-toggle="tab" href="#new" role="tab" aria-controls="new"
                    aria-selected="true">   Новые   </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="current-tab" data-toggle="tab" href="#current" role="tab" aria-controls="current"
                    aria-selected="false">   Текущие </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="done-tab" data-toggle="tab" href="#done" role="tab" aria-controls="done"
                    aria-selected="false">Выполненные</a>
        </ul>
        <div class="tab-content" id="myTabContent">
            <!-- Отсюда начинается новые-->
            <div class="tab-pane fade show active" id="new" role="tabpanel" aria-labelledby="new-tab">
                {% if not new_orders %}
                <br>
                <div id="border">
                    <div class="h3">
                        <p>Пусто ️🗑️</p>
                    </div>
                </div>
                {% endif %}

                {% for order in new_orders %}
                <br>
                <div id="border">
                    <div id="border1">
                        <p>Услуга: {{order.service}}</p>
                    </div>
                    <div id="border1">
                        <p>Пациентка: {{order.patient}}</p>
                    </div>
                    <div id="border1">
                        <p>Палата: {{order.patient.ward}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- Отсюда начинаются текущие-->
            <div class="tab-pane fade" id="current" role="tabpanel" aria-labelledby="current-tab">
                {% if not in_proc_orders %}
                <br>
                <div id="border">
                    <div class="h3">
                        <p>Пусто ️🗑️</p>
                    </div>
                </div>
                {% endif %}

                {% for order in in_proc_orders %}
                <br>
                <div id="border">
                    <div id="border1">
                        <p>Услуга: {{order.service}}</p>
                    </div>
                    <div id="border1">
                        <p>Пациентка: {{order.patient}}</p>
                    </div>
                    <div id="border1">
                        <p>Палата: {{order.patient.ward}}</p>
                    </div>
                    <div id="border1">
                        <p>Работник: {{order.worker}}</p>
                    </div>
                    <div id="border1">
                        <p>Время выполнения:
                            <br>
                            {{order.opening_date|date:"d.m.Y - H:i"}}
                            <br>
                            ...
                        </p>
                    </div>
                    <form action="{% url 'manager:home' %}" method="post">
                        {% csrf_token %}
                        <div id="bc"><button type="sumbit" class="btn btn-default" name="close-order" value="{{order.id}}">Закрыть
                                заявку</button></div>
                    </form>
                </div>
                {% endfor %}
            </div>
            <!-- Отсюда начинаются выполненные-->
            <div class="tab-pane fade" id="done" role="tabpanel" aria-labelledby="done-tab">
                {% if not done_orders %}
                <br>
                <div id="border">
                    <div class="h3">
                        <p>Пусто ️🗑️</p>
                    </div>
                </div>
                {% endif %}

                {% for order in done_orders %}
                <br>
                <div id="border">
                    <div id="border1">
                        <p>Услуга: {{order.service}}</p>
                    </div>
                    <div id="border1">
                        <p>Пациентка: {{order.patient}}</p>
                    </div>
                    <div id="border1">
                        <p>Палата: {{order.patient.ward}}</p>
                    </div>
                    <div id="border1">
                        <p>Работник: {{order.worker}}</p>
                    </div>
                    <div id="border1">
                        <p>Время выполнения:
                            <br>
                            {{order.opening_date|date:"d.m.Y - H:i"}}
                            <br>
                            {{order.closing_date|date:"d.m.Y - H:i"}}</p>
                    </div>
                    <div id="border1">
                        <p>Комментарий:<br>{{order.report}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

manager/templates/manager/medworker_sign_up.html
{% extends 'base.html' %}


{% block title %}
<title>Регистрация работника</title>
{% endblock title %}


{% block content %}

<div class="container">
    <form action="{% url 'manager:home' %}">
        <button type="submit" class="btn btn-default">Назад</button>
    </form>
    <div class="h1">Регистрация работника</div><br>
    <form method="post">
        {% csrf_token %}
        <div><input type="text" class="form-control" placeholder="Фамилия" name="last_name" maxlength="100" required=""
                id="id_last_name"></div><br>
        <div><input type="text" class="form-control" placeholder="Имя" name="first_name" maxlength="100" required="" id="id_first_name"></div><br>
        <div><input type="text" class="form-control" placeholder="Отчество" name="middle_name" maxlength="100" required=""
                id="id_middle_name"></div><br>
        <div class="input-group mb-3">
            <select class="custom-select" name="position" required id="id_position">
                {% for select in form.position %}
                <p>{{select}}</p>
                {% endfor %}
            </select>
        </div>
        <div><button type="submit" class="btn btn-default">Сохранить</button></div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/patient_sign_up.html
{% extends 'base.html' %}


{% block title %}
<title>Регистрация пациентки</title>
{% endblock title %}


{% block content %}

<div class="container">
    <form action="{% url 'manager:home' %}">
        <button type="submit" class="btn btn-default">Назад</button>
    </form>
    <div class="h1">Регистрация пациентки</div><br>
    <form method="post">
        {% csrf_token %}
        <div><input type="text" class="form-control" placeholder="Фамилия" name="last_name" maxlength="100" required=""
                id="id_last_name"></div><br>
        <div><input type="text" class="form-control" placeholder="Имя" name="first_name" maxlength="100" required="" id="id_first_name"></div><br>
        <div><input type="text" class="form-control" placeholder="Отчество" name="middle_name" maxlength="100" required=""
                id="id_middle_name"></div><br>
        <div><input type="date" class="form-control" name="birth_date" required=""
                id="id_birth_date"></div><br>
        {% comment %} <input type="date" name="birth_date" required="" id="id_birth_date"> {% endcomment %}
        <div class="form-group">
            <textarea class="form-control" name="address" rows="3" required="" id="id_address" placeholder="Адрес"></textarea>
        </div>
        <div><input type="text" class="form-control" placeholder="Номер телефона" name="contact_phone"
                maxlength="16" required="" id="id_contact_phone"></div><br>
        <div class="input-group mb-3">
            <select class="custom-select" name="ward" required="" id="id_ward">
                {% for select in form.ward %}
                <p>{{select}}</p>
                {% endfor %}
            </select>
        </div>
        <div><button type="submit" class="btn btn-default">Сохранить</button></div>
    </form>
</div>
{% endblock content %}

manager/templates/manager/sign_up.html
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>